### ISSUE TITLE
jamesdsp-9999.ebuild access violation failure

### ISSUE THREAD

**Issue by sandikata** [gentoobr/overlay#26]
Hello,

Is it there any workaround about this?

[log.txt](https://github.com/gentoobr/overlay/files/8600778/log.txt)

Regards

**Comment by leonardohn** [comment]
Thanks for reporting the problem. I just updated the ebuild, so it should work now. Unfortunately I can't test the ebuild because I'm currently using musl libc, for which I'm trying to add support for, so please let me know if it has any more issues.

**Comment by sandikata** [comment]
i will test it now.
