### ISSUE TITLE
Bump media-sound/spotifyd please

### ISSUE THREAD

**Issue by rayslava** [gentoobr/overlay#31]
0.3.5 has been released already: https://github.com/Spotifyd/spotifyd/releases/tag/v0.3.5
And this version works fine, while 0.3.4 has the `error[E0635]: unknown feature proc_macro_span_shrink` issue with latest `rustc`

**Comment by BGazotti** [comment]
I'll include it shortly.

I actually recommend using either `spotifyd-9999` (git version) or `media-sound/librespot` from this repo instead. Librespot is the backbone of spotifyd and currently actively mantained.
