### ISSUE TITLE
Bug in media-sound/librespot-9999 ebuild

### ISSUE THREAD

**Issue by rayslava** [gentoobr/overlay#32]
After advice from #31 I tried to build `librespot` but couldn't enable gstreamer and pulseaudio backends.
I guess `echo` is missing in the `configure` part: https://github.com/gentoobr/overlay/blob/master/media-sound/librespot/librespot-9999.ebuild#L404

**Comment by BGazotti** [comment]
It should be fixed now. Please test it yourself too and see if it builds and works properly.

**Comment by rayslava** [comment]
Now it works as intended.
Thank you!
